In [1]:
# Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Importing Dataset
data_set = pd.read_csv('bike.csv')

In [3]:
# Data set summary
print(data_set.info())

# Separation of Independent Variable(IV), Dependent Variable (DV)
X = data_set.iloc[:, [0, 3, 5]].values
y = data_set.iloc[:, -1].values
print(X[:5])
print(y[:5])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374115 entries, 0 to 374114
Data columns (total 9 columns):
Duration                374115 non-null int64
Start date              374115 non-null object
End date                374115 non-null object
Start station number    374115 non-null int64
Start station           374115 non-null object
End station number      374115 non-null int64
End station             374115 non-null object
Bike number             374115 non-null object
Member type             374115 non-null object
dtypes: int64(3), object(6)
memory usage: 25.7+ MB
None
[[  679 31302 31307]
 [  578 31232 31609]
 [  580 31232 31609]
 [  606 31104 31509]
 [  582 31129 31118]]
['Member' 'Casual' 'Casual' 'Member' 'Member']


In [4]:
# y has Categorical data hence needs Encoding
from sklearn.preprocessing import LabelEncoder
labelencoder_y =LabelEncoder()
y = labelencoder_y.fit_transform(y)
print("Sample y:",y[:5])
print("0 :",labelencoder_y.classes_[0])
print("1 :",labelencoder_y.classes_[1])

Sample y: [1 0 0 1 1]
0 : Casual
1 : Member


In [5]:
# Splitting of Data into Training & Testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [6]:
# Machine: Classifier | Classifier: Decision Tree
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', min_samples_leaf=4, random_state=0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=4, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=0,
            splitter='best')

In [7]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)


In [8]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[16396  8901]
 [10599 57633]]
